### ISSUE TITLE
npm readme can't view image. want help to fix this.

### ISSUE THREAD

**Issue by TonPC64** [Sellsuki/codechic-cli#15]
![image](https://user-images.githubusercontent.com/12834601/37242993-b9605e2a-24a4-11e8-9266-712289943dc5.png)

**Comment by biigpongsatorn** [comment]
![image](https://user-images.githubusercontent.com/10693658/37243205-758c4cbe-24a8-11e8-8bbe-6d720db8b9e4.png)
