### ISSUE TITLE
add badge npm verstion, download and trvis build to readme

### ISSUE THREAD

**Issue by TonPC64** [Sellsuki/codechic-cli#16]
example
<p align="center">
<a href="https://npmjs.com/package/begeta"><img src="https://img.shields.io/npm/v/begeta.svg?style=flat" alt="NPM version"></a>
<a href="https://npmjs.com/package/begeta"><img src="https://img.shields.io/npm/dm/begeta.svg?style=flat" alt="NPM downloads"></a>
<a href="https://travis-ci.org/Sellsuki/begeta"><img src="https://travis-ci.org/Sellsuki/begeta.svg?branch=master" alt="CircleCI"></a>
</p>

```
<p align="center">
<a href="https://npmjs.com/package/begeta"><img src="https://img.shields.io/npm/v/begeta.svg?style=flat" alt="NPM version"></a>
<a href="https://npmjs.com/package/begeta"><img src="https://img.shields.io/npm/dm/begeta.svg?style=flat" alt="NPM downloads"></a>
<a href="https://travis-ci.org/Sellsuki/begeta"><img src="https://travis-ci.org/Sellsuki/begeta.svg?branch=master" alt="CircleCI"></a>
</p>
```

**Comment by biigpongsatorn** [comment]
![image](https://user-images.githubusercontent.com/10693658/37243200-60f16e6a-24a8-11e8-9be9-faafff27ebe2.png)
